from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 570)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_deposit = QtWidgets.QPushButton(self.centralwidget)
        self.button_deposit.setGeometry(QtCore.QRect(50, 340, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_deposit.setFont(font)
        self.button_deposit.setObjectName("button_deposit")
        self.button_withdraw = QtWidgets.QPushButton(self.centralwidget)
        self.button_withdraw.setGeometry(QtCore.QRect(210, 340, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_withdraw.setFont(font)
        self.button_withdraw.setObjectName("button_withdraw")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(80, 30, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.input_amount = QtWidgets.QTextEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(70, 290, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_amount.setFont(font)
        self.input_amount.setObjectName("input_amount")
        self.label_Depo = QtWidgets.QLabel(self.centralwidget)
        self.label_Depo.setGeometry(QtCore.QRect(50, 260, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Depo.setFont(font)
        self.label_Depo.setObjectName("label_Depo")
        self.label_currentBalance = QtWidgets.QLabel(self.centralwidget)
        self.label_currentBalance.setGeometry(QtCore.QRect(10, 180, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_currentBalance.setFont(font)
        self.label_currentBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_currentBalance.setObjectName("label_currentBalance")
        self.label_errors = QtWidgets.QLabel(self.centralwidget)
        self.label_errors.setGeometry(QtCore.QRect(10, 400, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_errors.setFont(font)
        self.label_errors.setText("")
        self.label_errors.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_errors.setObjectName("label_errors")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 290, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_deposit.setText(_translate("MainWindow", "Deposit"))
        self.button_withdraw.setText(_translate("MainWindow", "Withdraw"))
        self.label_title.setText(_translate("MainWindow", "CSCI 1620 Banking App"))
        self.input_amount.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_Depo.setText(_translate("MainWindow", "Please enter an amount to deposit or withdraw"))
        self.label_currentBalance.setText(_translate("MainWindow", "Current Balance: $0.00"))
        self.label.setText(_translate("MainWindow", "$"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
